alter table if exists public.store_categories rename to store_menu_categories;
alter table if exists public.store_category_items rename to store_menu_category_items;
alter table if exists public.store_category_sort_indexes rename to store_menu_category_sort_indexes;
alter table if exists public.store_category_item_sort_indexes rename to store_menu_category_item_sort_indexes;
alter table if exists public.store_qr_codes rename to store_menu_qr_codes;

alter table if exists public.store_menu_category_items
  rename column store_category_id to store_menu_category_id;

alter table if exists public.store_menu_category_item_sort_indexes
  rename column store_category_id to store_menu_category_id;

alter table if exists public.store_menu_category_item_sort_indexes
  rename column store_category_item_id to store_menu_category_item_id;

alter table if exists public.stores
  rename column slug to menu_slug;

alter table if exists public.stores
  rename column seo_title to menu_seo_title;

alter table if exists public.stores
  rename column seo_description to menu_seo_description;

alter index if exists public.stores_slug_key rename to stores_menu_slug_key;

alter table if exists public.stores
  rename constraint stores_slug_format_check to stores_menu_slug_format_check;

alter table if exists public.store_menu_categories
  rename constraint store_categories_store_id_fkey to store_menu_categories_store_id_fkey;

alter table if exists public.store_menu_category_items
  rename constraint store_category_items_store_id_fkey to store_menu_category_items_store_id_fkey;

alter table if exists public.store_menu_category_items
  rename constraint store_category_items_store_category_id_fkey to store_menu_category_items_store_menu_category_id_fkey;

alter table if exists public.store_menu_category_sort_indexes
  rename constraint store_category_sort_indexes_store_id_fkey to store_menu_category_sort_indexes_store_id_fkey;

alter table if exists public.store_menu_category_sort_indexes
  rename constraint store_category_sort_indexes_category_id_fkey to store_menu_category_sort_indexes_category_id_fkey;

alter table if exists public.store_menu_category_item_sort_indexes
  rename constraint store_category_item_sort_indexes_store_category_id_fkey to store_menu_category_item_sort_indexes_store_menu_category_id_fkey;

alter table if exists public.store_menu_category_item_sort_indexes
  rename constraint store_category_item_sort_indexes_store_category_item_id_fkey to store_menu_category_item_sort_indexes_store_menu_category_item_id_fkey;

alter table if exists public.store_menu_qr_codes
  rename constraint store_qr_codes_store_id_fkey to store_menu_qr_codes_store_id_fkey;

create table if not exists public.store_menu_slug_redirects (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on update cascade on delete cascade,
  slug text not null,
  source text not null default 'manual_change',
  created_at timestamp with time zone not null default now(),
  constraint store_menu_slug_redirects_slug_key unique (slug),
  constraint store_menu_slug_redirects_slug_format_check check (
    length(slug) between 3 and 60
    and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
    and slug <> all(array[
      'new',
      'edit',
      'admin',
      'login',
      'signup',
      'settings',
      'pricing',
      'api',
      'www',
      'app',
      'help',
      'support'
    ])
  )
);

create or replace function public.enforce_store_menu_slug_ref_uniqueness()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  conflicting_id uuid;
begin
  if tg_table_name = 'stores' then
    select r.store_id
    into conflicting_id
    from public.store_menu_slug_redirects r
    where r.slug = new.menu_slug
      and r.store_id <> new.id
    limit 1;

    if found then
      raise exception 'That link is already taken.' using errcode = 'P0001';
    end if;

    return new;
  end if;

  select s.id
  into conflicting_id
  from public.stores s
  where s.menu_slug = new.slug
    and s.id <> new.store_id
  limit 1;

  if found then
    raise exception 'That link is already taken.' using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_stores_menu_slug_ref_uniqueness on public.stores;
create trigger enforce_stores_menu_slug_ref_uniqueness
before insert or update of menu_slug on public.stores
for each row
execute function public.enforce_store_menu_slug_ref_uniqueness();

drop trigger if exists enforce_store_menu_slug_redirects_ref_uniqueness on public.store_menu_slug_redirects;
create trigger enforce_store_menu_slug_redirects_ref_uniqueness
before insert or update of slug, store_id on public.store_menu_slug_redirects
for each row
execute function public.enforce_store_menu_slug_ref_uniqueness();

insert into public.store_menu_slug_redirects (store_id, slug, source)
select id, menu_slug, 'initial_backfill'
from public.stores
on conflict (slug) do nothing;

alter table public.store_menu_slug_redirects enable row level security;

grant all on table public.store_menu_slug_redirects to authenticated;
grant all on table public.store_menu_slug_redirects to service_role;
grant usage, select on sequence public.store_menu_slug_redirects_id_seq to authenticated;
grant usage, select on sequence public.store_menu_slug_redirects_id_seq to service_role;

create policy "Users can view slug redirects for their store menus"
on public.store_menu_slug_redirects
for select
using (
  store_id in (
    select s.id
    from public.stores s
    where s.user_id = auth.uid()
  )
);

create policy "Users can create slug redirects for their store menus"
on public.store_menu_slug_redirects
for insert
with check (
  store_id in (
    select s.id
    from public.stores s
    where s.user_id = auth.uid()
  )
);

create policy "Users can update slug redirects for their store menus"
on public.store_menu_slug_redirects
for update
using (
  store_id in (
    select s.id
    from public.stores s
    where s.user_id = auth.uid()
  )
)
with check (
  store_id in (
    select s.id
    from public.stores s
    where s.user_id = auth.uid()
  )
);

create policy "Users can delete slug redirects for their store menus"
on public.store_menu_slug_redirects
for delete
using (
  store_id in (
    select s.id
    from public.stores s
    where s.user_id = auth.uid()
  )
);
