alter table public.menu_qr_codes
add column if not exists encoded_url text;

alter table public.menus
add constraint menus_slug_format_check
check (
  slug is null
  or (
    length(slug) between 3 and 60
    and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
    and slug <> all(array[
      'new',
      'edit',
      'admin',
      'login',
      'signup',
      'settings',
      'pricing',
      'api',
      'www',
      'app',
      'help',
      'support'
    ])
  )
) not valid;

create table if not exists public.menu_slug_redirects (
  id bigint generated by default as identity primary key,
  menu_id uuid not null references public.menus(id) on update cascade on delete cascade,
  slug text not null,
  source text not null default 'manual_change',
  created_at timestamp with time zone not null default now(),
  constraint menu_slug_redirects_slug_key unique (slug),
  constraint menu_slug_redirects_slug_format_check check (
    length(slug) between 3 and 60
    and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
    and slug <> all(array[
      'new',
      'edit',
      'admin',
      'login',
      'signup',
      'settings',
      'pricing',
      'api',
      'www',
      'app',
      'help',
      'support'
    ])
  )
);

create or replace function public.enforce_menu_slug_ref_uniqueness()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  conflicting_id uuid;
begin
  if tg_table_name = 'menus' then
    if new.slug is null then
      return new;
    end if;

    select r.menu_id
    into conflicting_id
    from public.menu_slug_redirects r
    where r.slug = new.slug
      and r.menu_id <> new.id
    limit 1;

    if found then
      raise exception 'That link is already taken.' using errcode = 'P0001';
    end if;

    return new;
  end if;

  select m.id
  into conflicting_id
  from public.menus m
  where m.slug = new.slug
    and m.id <> new.menu_id
  limit 1;

  if found then
    raise exception 'That link is already taken.' using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_menus_slug_ref_uniqueness on public.menus;
create trigger enforce_menus_slug_ref_uniqueness
before insert or update of slug on public.menus
for each row
execute function public.enforce_menu_slug_ref_uniqueness();

drop trigger if exists enforce_menu_slug_redirects_ref_uniqueness on public.menu_slug_redirects;
create trigger enforce_menu_slug_redirects_ref_uniqueness
before insert or update of slug, menu_id on public.menu_slug_redirects
for each row
execute function public.enforce_menu_slug_ref_uniqueness();

insert into public.menu_slug_redirects (menu_id, slug, source)
select id, slug, 'initial_backfill'
from public.menus
where slug is not null
on conflict (slug) do nothing;

alter table public.menu_slug_redirects enable row level security;

grant all on table public.menu_slug_redirects to authenticated;
grant all on table public.menu_slug_redirects to service_role;
grant usage, select on sequence public.menu_slug_redirects_id_seq to authenticated;
grant usage, select on sequence public.menu_slug_redirects_id_seq to service_role;

create policy "Users can view slug redirects for their menus"
on public.menu_slug_redirects
for select
using (
  menu_id in (
    select m.id
    from public.menus m
    join public.businesses b on b.id = m.business_id
    where b.user_id = auth.uid()
  )
);

create policy "Users can create slug redirects for their menus"
on public.menu_slug_redirects
for insert
with check (
  menu_id in (
    select m.id
    from public.menus m
    join public.businesses b on b.id = m.business_id
    where b.user_id = auth.uid()
  )
);

create policy "Users can update slug redirects for their menus"
on public.menu_slug_redirects
for update
using (
  menu_id in (
    select m.id
    from public.menus m
    join public.businesses b on b.id = m.business_id
    where b.user_id = auth.uid()
  )
)
with check (
  menu_id in (
    select m.id
    from public.menus m
    join public.businesses b on b.id = m.business_id
    where b.user_id = auth.uid()
  )
);

create policy "Users can delete slug redirects for their menus"
on public.menu_slug_redirects
for delete
using (
  menu_id in (
    select m.id
    from public.menus m
    join public.businesses b on b.id = m.business_id
    where b.user_id = auth.uid()
  )
);

create or replace function public.update_menu_settings(
  p_menu_id uuid,
  p_name text,
  p_slug text
)
returns public.menus
language plpgsql
security definer
set search_path = public
as $$
declare
  current_menu public.menus%rowtype;
  updated_menu public.menus%rowtype;
  normalized_slug text := trim(p_slug);
  conflicting_menu_id uuid;
begin
  select m.*
  into current_menu
  from public.menus m
  join public.businesses b on b.id = m.business_id
  where m.id = p_menu_id
    and b.user_id = auth.uid()
  for update;

  if not found then
    raise exception 'Menu not found.' using errcode = 'P0001';
  end if;

  select m.id
  into conflicting_menu_id
  from public.menus m
  where m.slug = normalized_slug
    and m.id <> p_menu_id
  limit 1;

  if found then
    raise exception 'That link is already taken.' using errcode = 'P0001';
  end if;

  select r.menu_id
  into conflicting_menu_id
  from public.menu_slug_redirects r
  where r.slug = normalized_slug
    and r.menu_id <> p_menu_id
  limit 1;

  if found then
    raise exception 'That link is already taken.' using errcode = 'P0001';
  end if;

  if current_menu.slug is not null and current_menu.slug <> normalized_slug then
    insert into public.menu_slug_redirects (menu_id, slug, source)
    values (p_menu_id, current_menu.slug, 'manual_change')
    on conflict (slug) do nothing;
  end if;

  delete from public.menu_slug_redirects
  where menu_id = p_menu_id
    and slug = normalized_slug;

  update public.menus
  set name = p_name,
      slug = normalized_slug
  where id = p_menu_id
  returning * into updated_menu;

  return updated_menu;
end;
$$;

grant execute on function public.update_menu_settings(uuid, text, text) to authenticated;
grant execute on function public.update_menu_settings(uuid, text, text) to service_role;
