create extension if not exists "pgcrypto";

create table public.businesses (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  constraint businesses_user_id_key unique (user_id)
);

create table public.menus (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  name text not null
);

create table public.menu_qr_codes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  menu_id uuid not null references public.menus (id) on delete cascade,
  public_url text not null,
  constraint menu_qr_codes_menu_id_key unique (menu_id)
);

create table public.menu_categories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  menu_id uuid not null references public.menus (id) on delete cascade,
  name text not null,
  description text
);

create table public.menu_category_sort_indexes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  menu_id uuid not null references public.menus (id) on delete cascade,
  category_id bigint not null references public.menu_categories (id) on delete cascade,
  order_index integer not null,
  constraint menu_category_sort_indexes_category_id_key unique (category_id),
  constraint menu_category_sort_indexes_menu_id_order_index_key unique (menu_id, order_index)
);

create table public.menu_category_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  menu_id uuid not null references public.menus (id) on delete cascade,
  menu_category_id bigint not null references public.menu_categories (id) on delete cascade,
  name text not null,
  description text,
  price numeric(10,2) not null check (price >= 0),
  image_url text
);

create table public.menu_category_item_sort_indexes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  menu_category_id bigint not null references public.menu_categories (id) on delete cascade,
  menu_category_item_id bigint not null references public.menu_category_items (id) on delete cascade,
  order_index integer not null,
  constraint menu_category_item_sort_indexes_menu_category_item_id_key unique (menu_category_item_id),
  constraint menu_category_item_sort_indexes_menu_category_id_order_index_key unique (menu_category_id, order_index)
);

create table public.user_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  feedback text not null
);

create index menus_business_id_idx on public.menus (business_id);
create index menu_categories_menu_id_idx on public.menu_categories (menu_id);
create index menu_category_items_menu_id_idx on public.menu_category_items (menu_id);
create index menu_category_items_menu_category_id_idx on public.menu_category_items (menu_category_id);
create index menu_category_sort_indexes_menu_id_idx on public.menu_category_sort_indexes (menu_id);
create index menu_category_item_sort_indexes_menu_category_id_idx
  on public.menu_category_item_sort_indexes (menu_category_id);
create index user_feedback_user_id_idx on public.user_feedback (user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_menu_category_items_updated_at
before update on public.menu_category_items
for each row
execute function public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('qr_codes', 'qr_codes', true)
on conflict (id) do nothing;
