


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."SUBSCRIPTION_STATUS" AS ENUM (
    'incomplete',
    'incomplete_expired',
    'trialing',
    'active',
    'past_due',
    'canceled',
    'unpaid',
    'paused'
);


ALTER TYPE "public"."SUBSCRIPTION_STATUS" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."businesses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."businesses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."menu_category_item_sort_indexes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "menu_category_id" bigint NOT NULL,
    "order_index" bigint NOT NULL,
    "menu_category_item_id" bigint NOT NULL
);


ALTER TABLE "public"."menu_category_item_sort_indexes" OWNER TO "postgres";


ALTER TABLE "public"."menu_category_item_sort_indexes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."category_items_indexes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."menu_category_sort_indexes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "category_id" bigint NOT NULL,
    "order_index" bigint NOT NULL,
    "menu_id" "uuid" NOT NULL
);


ALTER TABLE "public"."menu_category_sort_indexes" OWNER TO "postgres";


ALTER TABLE "public"."menu_category_sort_indexes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."category_orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_feedback" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "feedback" "text" NOT NULL
);


ALTER TABLE "public"."user_feedback" OWNER TO "postgres";


ALTER TABLE "public"."user_feedback" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feedback_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."menu_categories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "menu_id" "uuid" NOT NULL
);


ALTER TABLE "public"."menu_categories" OWNER TO "postgres";


COMMENT ON TABLE "public"."menu_categories" IS 'Categories created for each menu.';



CREATE TABLE IF NOT EXISTS "public"."menu_category_items" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "price" numeric NOT NULL,
    "image_url" "text",
    "menu_category_id" bigint NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "menu_id" "uuid" NOT NULL
);


ALTER TABLE "public"."menu_category_items" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."menu_qr_codes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "public_url" "text" NOT NULL,
    "menu_id" "uuid" NOT NULL
);


ALTER TABLE "public"."menu_qr_codes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."menus" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "business_id" "uuid" NOT NULL
);


ALTER TABLE "public"."menus" OWNER TO "postgres";


ALTER TABLE "public"."menu_categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."restaurant_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."menu_category_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."restaurant_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."menu_qr_codes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."restaurant_qr_codes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "current_period_start" timestamp with time zone NOT NULL,
    "current_period_end" timestamp with time zone NOT NULL,
    "stripe_customer_id" "text" NOT NULL,
    "stripe_price_id" "text" NOT NULL,
    "stripe_subscription_id" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "status" "public"."SUBSCRIPTION_STATUS" NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "business_id" "uuid" NOT NULL
);


ALTER TABLE "public"."subscriptions" OWNER TO "postgres";


COMMENT ON TABLE "public"."subscriptions" IS 'Subscriptions for each place, determining if that place''s menu is public (subscribed) or not (unsubscribed).';



ALTER TABLE ONLY "public"."menu_category_item_sort_indexes"
    ADD CONSTRAINT "category_items_indexes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menu_category_sort_indexes"
    ADD CONSTRAINT "category_orders_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_feedback"
    ADD CONSTRAINT "feedback_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menus"
    ADD CONSTRAINT "menus_2_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menu_categories"
    ADD CONSTRAINT "place_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menu_category_items"
    ADD CONSTRAINT "place_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."businesses"
    ADD CONSTRAINT "places_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menu_qr_codes"
    ADD CONSTRAINT "qr_codes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_business_id_key" UNIQUE ("business_id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."businesses"
    ADD CONSTRAINT "business_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."menu_category_item_sort_indexes"
    ADD CONSTRAINT "category_items_indexes_category_id_fkey" FOREIGN KEY ("menu_category_id") REFERENCES "public"."menu_categories"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_feedback"
    ADD CONSTRAINT "feedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."menu_category_item_sort_indexes"
    ADD CONSTRAINT "item_sort_indexes_item_id_fkey" FOREIGN KEY ("menu_category_item_id") REFERENCES "public"."menu_category_items"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."menu_categories"
    ADD CONSTRAINT "menu_categories_menu_id_fkey" FOREIGN KEY ("menu_id") REFERENCES "public"."menus"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."menu_category_items"
    ADD CONSTRAINT "menu_category_items_menu_category_id_fkey" FOREIGN KEY ("menu_category_id") REFERENCES "public"."menu_categories"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."menu_category_items"
    ADD CONSTRAINT "menu_category_items_menu_id_fkey" FOREIGN KEY ("menu_id") REFERENCES "public"."menus"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."menu_category_sort_indexes"
    ADD CONSTRAINT "menu_category_sort_indexes_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."menu_categories"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."menu_category_sort_indexes"
    ADD CONSTRAINT "menu_category_sort_indexes_menu_id_fkey" FOREIGN KEY ("menu_id") REFERENCES "public"."menus"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."menu_qr_codes"
    ADD CONSTRAINT "menu_qr_codes_menu_id_fkey" FOREIGN KEY ("menu_id") REFERENCES "public"."menus"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."menus"
    ADD CONSTRAINT "menus_2_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "public"."businesses"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "public"."businesses"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



CREATE POLICY "Users can create QR codes for their menus" ON "public"."menu_qr_codes" FOR INSERT WITH CHECK (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can create categories for their menus" ON "public"."menu_categories" FOR INSERT WITH CHECK (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can create item sort indexes for their categories" ON "public"."menu_category_item_sort_indexes" FOR INSERT WITH CHECK (("menu_category_id" IN ( SELECT "mc"."id"
   FROM (("public"."menu_categories" "mc"
     JOIN "public"."menus" "m" ON (("mc"."menu_id" = "m"."id")))
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can create items for their menu categories" ON "public"."menu_category_items" FOR INSERT WITH CHECK (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can create menus for their own businesses" ON "public"."menus" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."businesses"
  WHERE (("businesses"."id" = "menus"."business_id") AND ("businesses"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can create sort indexes for their menus" ON "public"."menu_category_sort_indexes" FOR INSERT WITH CHECK (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can create their own businesses" ON "public"."businesses" FOR INSERT WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "Users can create their own feedback" ON "public"."user_feedback" FOR INSERT WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "Users can delete QR codes from their menus" ON "public"."menu_qr_codes" FOR DELETE USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can delete categories from their menus" ON "public"."menu_categories" FOR DELETE USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can delete item sort indexes from their categories" ON "public"."menu_category_item_sort_indexes" FOR DELETE USING (("menu_category_id" IN ( SELECT "mc"."id"
   FROM (("public"."menu_categories" "mc"
     JOIN "public"."menus" "m" ON (("mc"."menu_id" = "m"."id")))
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can delete items from their menu categories" ON "public"."menu_category_items" FOR DELETE USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can delete menus for their own businesses" ON "public"."menus" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM "public"."businesses"
  WHERE (("businesses"."id" = "menus"."business_id") AND ("businesses"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete sort indexes from their menus" ON "public"."menu_category_sort_indexes" FOR DELETE USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can delete their own businesses" ON "public"."businesses" FOR DELETE USING (("user_id" = "auth"."uid"()));



CREATE POLICY "Users can delete their own feedback" ON "public"."user_feedback" FOR DELETE USING (("user_id" = "auth"."uid"()));



CREATE POLICY "Users can read categories from their menus" ON "public"."menu_categories" FOR SELECT USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can read their own subscriptions" ON "public"."subscriptions" FOR SELECT USING (("business_id" IN ( SELECT "businesses"."id"
   FROM "public"."businesses"
  WHERE ("businesses"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can update QR codes from their menus" ON "public"."menu_qr_codes" FOR UPDATE USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"())))) WITH CHECK (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can update categories from their menus" ON "public"."menu_categories" FOR UPDATE USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"())))) WITH CHECK (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can update item sort indexes from their categories" ON "public"."menu_category_item_sort_indexes" FOR UPDATE USING (("menu_category_id" IN ( SELECT "mc"."id"
   FROM (("public"."menu_categories" "mc"
     JOIN "public"."menus" "m" ON (("mc"."menu_id" = "m"."id")))
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"())))) WITH CHECK (("menu_category_id" IN ( SELECT "mc"."id"
   FROM (("public"."menu_categories" "mc"
     JOIN "public"."menus" "m" ON (("mc"."menu_id" = "m"."id")))
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can update items from their menu categories" ON "public"."menu_category_items" FOR UPDATE USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"())))) WITH CHECK (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can update menus for their own businesses" ON "public"."menus" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."businesses"
  WHERE (("businesses"."id" = "menus"."business_id") AND ("businesses"."user_id" = "auth"."uid"()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."businesses"
  WHERE (("businesses"."id" = "menus"."business_id") AND ("businesses"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can update sort indexes from their menus" ON "public"."menu_category_sort_indexes" FOR UPDATE USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"())))) WITH CHECK (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can update their own businesses" ON "public"."businesses" FOR UPDATE USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "Users can update their own feedback" ON "public"."user_feedback" FOR UPDATE USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "Users can view QR codes from their menus" ON "public"."menu_qr_codes" FOR SELECT USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can view item sort indexes from their categories" ON "public"."menu_category_item_sort_indexes" FOR SELECT USING (("menu_category_id" IN ( SELECT "mc"."id"
   FROM (("public"."menu_categories" "mc"
     JOIN "public"."menus" "m" ON (("mc"."menu_id" = "m"."id")))
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can view items from their menu categories" ON "public"."menu_category_items" FOR SELECT USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can view menus for their own businesses" ON "public"."menus" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."businesses"
  WHERE (("businesses"."id" = "menus"."business_id") AND ("businesses"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can view sort indexes from their menus" ON "public"."menu_category_sort_indexes" FOR SELECT USING (("menu_id" IN ( SELECT "m"."id"
   FROM ("public"."menus" "m"
     JOIN "public"."businesses" "b" ON (("m"."business_id" = "b"."id")))
  WHERE ("b"."user_id" = "auth"."uid"()))));



CREATE POLICY "Users can view their own businesses" ON "public"."businesses" FOR SELECT USING (("user_id" = "auth"."uid"()));



CREATE POLICY "Users can view their own feedback" ON "public"."user_feedback" FOR SELECT USING (("user_id" = "auth"."uid"()));



ALTER TABLE "public"."businesses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."menu_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."menu_category_item_sort_indexes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."menu_category_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."menu_category_sort_indexes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."menu_qr_codes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."menus" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_feedback" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."businesses" TO "anon";
GRANT ALL ON TABLE "public"."businesses" TO "authenticated";
GRANT ALL ON TABLE "public"."businesses" TO "service_role";



GRANT ALL ON TABLE "public"."menu_category_item_sort_indexes" TO "anon";
GRANT ALL ON TABLE "public"."menu_category_item_sort_indexes" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_category_item_sort_indexes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."category_items_indexes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."category_items_indexes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."category_items_indexes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."menu_category_sort_indexes" TO "anon";
GRANT ALL ON TABLE "public"."menu_category_sort_indexes" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_category_sort_indexes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."category_orders_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."category_orders_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."category_orders_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_feedback" TO "anon";
GRANT ALL ON TABLE "public"."user_feedback" TO "authenticated";
GRANT ALL ON TABLE "public"."user_feedback" TO "service_role";



GRANT ALL ON SEQUENCE "public"."feedback_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."feedback_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."feedback_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."menu_categories" TO "anon";
GRANT ALL ON TABLE "public"."menu_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_categories" TO "service_role";



GRANT ALL ON TABLE "public"."menu_category_items" TO "anon";
GRANT ALL ON TABLE "public"."menu_category_items" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_category_items" TO "service_role";



GRANT ALL ON TABLE "public"."menu_qr_codes" TO "anon";
GRANT ALL ON TABLE "public"."menu_qr_codes" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_qr_codes" TO "service_role";



GRANT ALL ON TABLE "public"."menus" TO "anon";
GRANT ALL ON TABLE "public"."menus" TO "authenticated";
GRANT ALL ON TABLE "public"."menus" TO "service_role";



GRANT ALL ON SEQUENCE "public"."restaurant_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."restaurant_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."restaurant_categories_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."restaurant_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."restaurant_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."restaurant_items_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."restaurant_qr_codes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."restaurant_qr_codes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."restaurant_qr_codes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."subscriptions" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


  create policy "Anyone can view QR codes"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'qr_codes'::text));



  create policy "Users can delete QR codes for their menus"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'qr_codes'::text) AND ((storage.foldername(name))[2] IN ( SELECT (m.id)::text AS id
   FROM (public.menus m
     JOIN public.businesses b ON ((m.business_id = b.id)))
  WHERE (b.user_id = auth.uid())))));



  create policy "Users can update QR codes for their menus"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'qr_codes'::text) AND ((storage.foldername(name))[2] IN ( SELECT (m.id)::text AS id
   FROM (public.menus m
     JOIN public.businesses b ON ((m.business_id = b.id)))
  WHERE (b.user_id = auth.uid())))))
with check (((bucket_id = 'qr_codes'::text) AND ((storage.foldername(name))[2] IN ( SELECT (m.id)::text AS id
   FROM (public.menus m
     JOIN public.businesses b ON ((m.business_id = b.id)))
  WHERE (b.user_id = auth.uid())))));



  create policy "Users can upload QR codes for their menus"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'qr_codes'::text) AND ((storage.foldername(name))[2] IN ( SELECT (m.id)::text AS id
   FROM (public.menus m
     JOIN public.businesses b ON ((m.business_id = b.id)))
  WHERE (b.user_id = auth.uid())))));



